### PR TITLE
Fix linting

### LINKED ISSUE #97: Fix linting
The linting job in the PR validation fails and the reported problems should be fixed.

Steps to do:
- install `golangci-lint`
- execute `golangci-lint` in the `github.com/cloudfoundry/loggregator-agent-release/src` directory
- fix all the findings

### PR DESCRIPTION
**Pull request by chombium**
I've run golangci-lint and fixed all of the findings.

Remarks to these change:
- there are many functions which return error and are called in defer functions or run as goroutines. I've added a a comment to  ignored these findings
- there are many functions which are not used which I've commented out as I'm not sure if they should be kept or not
- There is a [RefreshTokenKeys](https://github.com/cloudfoundry/log-cache-release/blob/main/src/internal/auth/uaa_client.go#L88-L173) function in `uaa_client.go` which is called once as a [goroutine](https://github.com/cloudfoundry/log-cache-release/blob/main/src/internal/auth/uaa_client.go#L220) and once [directly](https://github.com/cloudfoundry/log-cache-release/blob/main/src/internal/auth/uaa_client.go#L255). Adding error check to the "normal" call makes few tests break as there are some timing issues. IMO it would we good if we refactor this in order to avoid problems. Do you thing this worth taking a look?

Fixes #97 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [x] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

### CODE REVIEW

File: src/internal/auth/cf_auth_middleware.go [hunk 1]
```diff
@@ -117,11 +117,14 @@ func (m CFAuthMiddlewareProvider) Middleware(h http.Handler) http.Handler {
...
 			w.WriteHeader(http.StatusBadRequest)
 
-			json.NewEncoder(w).Encode(&promqlErrorBody{
+			err = json.NewEncoder(w).Encode(&promqlErrorBody{
 				Status:    "error",
 				ErrorType: "bad_data",
 				Error:     err.Error(),
 			})
+			if err != nil {
+				log.Printf("bad data: %v", err)
```
Comment (ctlong) [inline src/internal/auth/cf_auth_middleware.go:126]: Can you please add a `\n` to the end of this string?

File: src/internal/auth/cf_auth_middleware_test.go [hunk 2]
```diff
@@ -397,9 +397,9 @@ var _ = Describe("CfAuthMiddleware", func() {
 type spyOauth2ClientReader struct {
 	token         string
 	isAdminResult bool
-	client        string
-	user          string
-	err           error
+	// client        string
+	// user          string
```
Comment (ctlong) [inline src/internal/auth/cf_auth_middleware_test.go:401]: If they're unused, please go ahead and delete these variables :)

File: src/internal/auth/uaa_client_test.go [hunk 3]
```diff
@@ -107,21 +105,26 @@ var _ = Describe("UAAClient", func() {
 			payload := tc.BuildValidPayload("logs.admin")
 			token := tc.CreateSignedToken(payload)
 
-			tc.uaaClient.Read(withBearer(token))
-			tc.uaaClient.Read(withBearer(token))
+			_, err := tc.uaaClient.Read(withBearer(token))
+			Expect(err).ToNot(HaveOccurred())
+			Expect(err).ToNot(HaveOccurred())
```
Comment (ctlong) [inline src/internal/auth/uaa_client_test.go:110]: There's a duplicate line here.

File: src/internal/auth/uaa_client_test.go [hunk 4]
```diff
@@ -450,15 +461,15 @@ func generateLegitTokenKey(keyId string) mockTokenKey {
...
-		publicKey:  privateKey,
-		keyId:      keyId,
-	}
-}
+// 	return mockTokenKey{
+// 		privateKey: privateKey,
+// 		publicKey:  privateKey,
+// 		keyId:      keyId,
+// 	}
+// }
```
Comment (ctlong) [inline src/internal/auth/uaa_client_test.go:472]: If this function is no longer used, then please delete it :)

File: src/internal/auth/uaa_client_test.go [hunk 5]
```diff
@@ -691,30 +702,30 @@ func (s *spyHTTPClient) Do(r *http.Request) (*http.Response, error) {
...
+// 		defer s.mu.Unlock()
+// 		s.m[name] = v
+// 	}
+// }
+
+// func publicKeyExponentToString(privateKey *rsa.PrivateKey) string {
+// 	b := make([]byte, 8)
+// 	binary.LittleEndian.PutUint64(b, uint64(privateKey.PublicKey.E))
+// 	return base64.StdEncoding.EncodeToString(b[0:3])
+// }
```
Comment (ctlong) [inline src/internal/auth/uaa_client_test.go:728]: Please delete these unused functions.

File: src/internal/auth/uaa_client_test.go [hunk 6]
```diff
@@ -736,9 +747,9 @@ func keyPEMToString(privateKey *rsa.PrivateKey) (string, string) {
 	return publicKey, privateKeyString
 }
 
-func publicKeyModulusToString(privateKey *rsa.PrivateKey) string {
-	return base64.StdEncoding.EncodeToString(privateKey.PublicKey.N.Bytes())
-}
+// func publicKeyModulusToString(privateKey *rsa.PrivateKey) string {
+// 	return base64.StdEncoding.EncodeToString(privateKey.PublicKey.N.Bytes())
+// }
```
Comment (ctlong) [inline src/internal/auth/uaa_client_test.go:752]: Please delete this unused function.

File: src/internal/cache/store/store_benchmark_test.go [hunk 7]
```diff
@@ -151,14 +150,14 @@ func BenchmarkMetaWhileReading(b *testing.B) {
...
-	}
-}
+// func contextIsDone(ctx context.Context) bool {
+// 	select {
+// 	case <-ctx.Done():
+// 		return true
+// 	default:
+// 		return false
+// 	}
+// }
```
Comment (ctlong) [inline src/internal/cache/store/store_benchmark_test.go:160]: If unused, please delete.

File: src/internal/gateway/gateway.go [hunk 8]
```diff
@@ -179,7 +180,10 @@ func (g *Gateway) listenAndServe() {
 }
 
 func (g *Gateway) handleInfoEndpoint(w http.ResponseWriter, r *http.Request) {
-	w.Write([]byte(fmt.Sprintf(`{"version":"%s","vm_uptime":"%d"}`+"\n", g.logCacheVersion, g.uptimeFn())))
+	_, err := w.Write([]byte(fmt.Sprintf(`{"version":"%s","vm_uptime":"%d"}`+"\n", g.logCacheVersion, g.uptimeFn())))
+	if err != nil {
+		g.log.Fatalf("Cannot send result for the info endpoint")
```
Comment (ctlong) [inline src/internal/gateway/gateway.go:185]: Why should this be a fatal log when it wasn't before? Perhaps this should just be an error log.

File: src/internal/promql/promql.go [hunk 9]
```diff
@@ -26,7 +26,7 @@ type PromQL struct {
 	failureCounter    metrics.Counter
 	instantQueryTimer metrics.Gauge
 	rangeQueryTimer   metrics.Gauge
-	failures          int
+	// failures          int
```
Comment (ctlong) [inline src/internal/promql/promql.go:29]: Please delete if unused.

File: src/internal/promql/promql_test.go [hunk 10]
```diff
@@ -1370,10 +1370,10 @@ func (s *spyDataReader) ReadEnvelopeTypes() [][]logcache_v1.EnvelopeType {
...
+// func (s *spyDataReader) setRead(es [][]*loggregator_v2.Envelope, errs []error) {
+// 	s.mu.Lock()
+// 	defer s.mu.Unlock()
 
-	s.readResults = es
-	s.readErrs = errs
-}
+// 	s.readResults = es
+// 	s.readErrs = errs
+// }
```
Comment (ctlong) [inline src/internal/promql/promql_test.go:1379]: Please delete, if unused.

**Review by ctlong — CHANGES_REQUESTED** [review]
Thanks for making this PR @chombium! I've requested some changes, please have a look when you get a chance.

**Comment by chombium** [comment]
Hi @ctlong,

Thanks for your review. I've fixed all of the issues and re-run the unit tests and linter. Everything looks good on my machine :)

I've check the failing unit tests and compared the logs from he GH Workflow action and my local run and apart from my local run `Starting 16 workers...` and in the action `Starting 4 workers...` there are no other differences.

There is a small caveat in the way the uaa_client is refreshing uaa tokens. The function is  called as a goroutine [here](https://github.com/cloudfoundry/log-cache-release/blob/main/src/internal/auth/uaa_client.go#L220) in uaa_client.Read function and it is called directly many times. I think that there might be some timing issue after I added the error checking. Do you think that it's worth checking the problem or I can simply remove the error checks and add nolint:errcheck directives wherever `uaaClient.RefreshTokenKeys()` is called in a single test where `uaaClient.Read()` is called as well?

**Comment by ctlong** [comment]
@chombium thanks for making the changes. Tests are passing in GH actions 🎉 

I think it's okay to remove the error checks and add nolint:errcheck directives for that method of the uaaClient if it's causing problems.

Unfortunately, it appears that there's still one more error in the golangci-lint run by GH actions. Can you please check that out?

**Comment by chombium** [comment]
HI @ctlong , I've made the needed changes, now the linting should also be green. For the last finding in the linting checks I've set the MinVersion parameter for TLS, but as I saw that many people are complaining that have this finding as false positive, I've added a `//nolint:gosec` as well, so that it won't be reported anymore.

I've also checked the findings from `go vet`, but I couldn't fix it. I've googled a bit  and found the same function signature for the Seek function in few other projects including Prometheus it self. As there is no way to ignore vet findings, I guess we'll have to live  with it :-/

**Comment by chombium** [comment]
@ctlong Coild you please re-trigger the checks? The lint action timmed out loading packages and failed

**Review by Benjamintf1 — APPROVED** [review]

**Review by ctlong — APPROVED** [review]
